version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.13.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=10

  chrome:
    image: selenium/node-chrome:4.13.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSION=5
    ports:
      - "5900:5900"
    platform: linux/amd64

  firefox:
    image: selenium/node-firefox:4.13.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSION=5
    ports:
      - "5901:5900"
    platform: linux/amd64

  edge:
    image: selenium/node-edge:4.13.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSION=5
    ports:
      - "5902:5900"
    platform: linux/amd64
